import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
const browser = await chromium.launch({ headless: true, args: ['--no-sandbox'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, permissions: ['clipboard-read', 'clipboard-write'] });
const errors = [];
page.on('pageerror', error => errors.push(error.message));
await mkdir('artifacts', { recursive: true });
try {
  await page.goto('http://localhost:3000');
  await page.getByRole('heading', { name: /Good things start here/ }).waitFor();
  await page.waitForFunction(() => [...document.images].filter(i => i.loading !== 'lazy').every(i => i.complete && i.naturalWidth > 0));
  await page.screenshot({ path: 'artifacts/overview.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Pause animations' }).click();
  assert.equal(await page.locator('html').getAttribute('data-motion'), 'off');
  await page.reload();
  await page.getByRole('button', { name: 'Enable animations' }).waitFor();
  await page.getByRole('button', { name: 'Enable animations' }).click();
  await page.locator('.quick-card').filter({ hasText: 'Security hardening' }).click();
  await page.getByRole('dialog').waitFor();
  await page.getByRole('button', { name: 'Copy prompt', exact: true }).click();
  await page.getByRole('button', { name: 'Copied!', exact: true }).waitFor();
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /QUICK REPO WORKFLOW/);
  await page.getByRole('button', { name: 'Instructions', exact: true }).click();
  assert.match(await page.locator('dialog pre').innerText(), /Never perform destructive operations/);
  await page.getByRole('button', { name: 'Use prompt', exact: true }).click();
  assert.equal(await page.getByRole('combobox', { name: 'Session mode' }).inputValue(), 'coding');
  assert.match(await page.locator('#brief').inputValue(), /Repository:/);
  const nav = page.locator('.sidebar');
  for (const name of ['Agent & Prompt Station', 'My agents', 'Prompt library', 'Sessions', 'Projects', 'Usage & analytics', 'Settings']) {
    await nav.locator('button.nav-item').filter({ hasText: name }).click();
    await page.locator('.page-art-banner').first().waitFor();
    const images = page.locator('main img');
    assert.ok(await images.count() > 0, `${name} has artwork`);
    await page.locator('.page-art-banner img').evaluate(img => img.decode());
    console.log(`PASS ${name}: illustrated page renders`);
  }
  await nav.getByRole('button', { name: 'Prompt library', exact: true }).click();
  await page.getByRole('combobox', { name: 'Filter category' }).selectOption('Repo optimization');
  assert.equal(await page.locator('.library-grid .agent-card').count(), 6);
  await page.getByRole('textbox', { name: 'Search the library' }).fill('Bug finder');
  assert.equal(await page.locator('.library-grid .agent-card').count(), 1);
  await page.getByRole('button', { name: 'Clear search' }).click();
  await page.screenshot({ path: 'artifacts/library.png', fullPage: true, animations: 'disabled' });
  const saved = await page.request.post('http://localhost:3000/api/station', { data: { action: 'saveAsset', name: 'Smoke test workflow', description: 'Verifies illustrated workflow persistence.', kind: 'prompt', category: 'Repo optimization', instructions: 'Review the repository and report confirmed security findings without exposing secrets.' } });
  assert.equal(saved.status(), 201);
  const asset = await saved.json();
  const list = await (await page.request.get('http://localhost:3000/api/station')).json();
  assert.ok(list.assets.some(a => a.id === asset.id));
  const share = await page.request.post('http://localhost:3000/api/station', { data: { action: 'share', id: asset.id, enabled: true } });
  assert.ok(share.ok());
  const shared = await share.json();
  console.log('Share response keys:', Object.keys(shared));
  const url = shared.url || (shared.token ? `/share/${shared.token}` : null);
  if (url) { const tab = await browser.newPage(); await tab.goto(new URL(url, 'http://localhost:3000').href); await tab.locator('.share-art').waitFor(); await tab.close(); }
  assert.ok((await page.request.post('http://localhost:3000/api/station', { data: { action: 'deleteAsset', id: asset.id } })).ok());
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await page.getByRole('heading', { name: /Good things start here/ }).waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No mobile horizontal overflow');
  await page.screenshot({ path: 'artifacts/mobile.png', fullPage: true, animations: 'disabled' });
  await page.getByRole('button', { name: 'Open navigation' }).click();
  await nav.getByRole('button', { name: 'Prompt library', exact: true }).click();
  await page.locator('.quick-grid.full').waitFor();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), 'No library mobile overflow');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  assert.equal(await page.locator('.banner-spark').evaluate(el => getComputedStyle(el).animationName), 'none');
  assert.deepEqual(errors, []);
  console.log('PASS quick prompt preview, coding mode, filters, persistence, sharing, mobile, motion and console checks');
} finally { await browser.close(); }
